import { z } from 'zod'

export const miracleQuerySchema = z.object({
  page:              z.coerce.number().int().positive().default(1),
  limit:             z.coerce.number().int().positive().max(100).default(20),
  q:                 z.string().max(200).optional(),
  continent:         z.enum(['EUROPA','AMERICA_NORD','AMERICA_SUD','AFRICA','ASIA','OCEANIA','MEDIO_ORIENTE']).optional(),
  countryId:         z.string().optional(),
  verificationLevel: z.enum(['STORICO','DIOCESANO','PONTIFICIO','SCIENTIFICO']).optional(),
  yearFrom:          z.coerce.number().int().optional(),
  yearTo:            z.coerce.number().int().optional(),
  isVisitable:       z.coerce.boolean().optional(),
  hasScience:        z.coerce.boolean().optional(),
  hasVideo:          z.coerce.boolean().optional(),
  lat:               z.coerce.number().optional(),
  lng:               z.coerce.number().optional(),
  radiusKm:          z.coerce.number().positive().max(5000).optional(),
  sortBy:            z.enum(['year','title','viewCount','featuredOrder']).default('featuredOrder'),
  sortDir:           z.enum(['asc','desc']).default('asc'),
})

export const createMiracleSchema = z.object({
  title:                    z.string().min(3).max(300).trim(),
  slug:                     z.string().min(3).max(300).regex(/^[a-z0-9-]+$/).optional(),
  location:                 z.string().min(2).max(300),
  city:                     z.string().max(200).optional(),
  state:                    z.string().max(200).optional(),
  continent:                z.enum(['EUROPA','AMERICA_NORD','AMERICA_SUD','AFRICA','ASIA','OCEANIA','MEDIO_ORIENTE']),
  countryId:                z.string().optional(),
  lat:                      z.number().min(-90).max(90).optional(),
  lng:                      z.number().min(-180).max(180).optional(),
  year:                     z.number().int().optional(),
  yearCa:                   z.string().max(50).optional(),
  verificationLevel:        z.enum(['STORICO','DIOCESANO','PONTIFICIO','SCIENTIFICO']),
  summary:                  z.string().min(20).max(3000),
  fullDescription:          z.string().min(50),
  context:                  z.string().optional(),
  miracle:                  z.string().optional(),
  aftermath:                z.string().optional(),
  scientificAnalysis:       z.string().optional(),
  tissueType:               z.string().max(300).optional(),
  bloodType:                z.string().max(20).optional(),
  analyzedBy:               z.string().max(300).optional(),
  analysisYear:             z.number().int().optional(),
  analysisInstitution:      z.string().max(300).optional(),
  ecclesiasticalRecognition: z.string().optional(),
  officialRecognition:      z.string().max(500).optional(),
  recognizedBy:             z.string().max(300).optional(),
  recognitionYear:          z.number().int().optional(),
  isVisitableToday:         z.boolean().default(false),
  visitingInfo:             z.string().optional(),
  conservedAt:              z.string().max(500).optional(),
  openingHours:             z.string().max(500).optional(),
  entryFee:                 z.string().max(200).optional(),
  accessInfo:               z.string().optional(),
  imageUrl:                 z.string().url().optional(),
  thumbnailUrl:             z.string().url().optional(),
  sources:                  z.array(z.string()).default([]),
  featuredOrder:            z.number().int().optional(),
  isPublished:              z.boolean().default(true),
})

export const updateMiracleSchema   = createMiracleSchema.partial()

export const createImageSchema = z.object({
  url:       z.string().url(),
  caption:   z.string().max(500).optional(),
  credit:    z.string().max(200).optional(),
  altText:   z.string().max(200).optional(),
  isCover:   z.boolean().default(false),
  sortOrder: z.number().int().default(0),
})

export const createVideoSchema = z.object({
  title:       z.string().min(3).max(300),
  url:         z.string().url(),
  embedUrl:    z.string().url().optional(),
  platform:    z.enum(['YOUTUBE','VIMEO','OTHER']).default('YOUTUBE'),
  videoId:     z.string().max(200).optional(),
  description: z.string().max(1000).optional(),
  duration:    z.number().int().positive().optional(),
  language:    z.string().max(5).optional(),
  sortOrder:   z.number().int().default(0),
})

export const createDocumentSchema = z.object({
  title:       z.string().min(3).max(300),
  description: z.string().max(1000).optional(),
  url:         z.string().url(),
  fileType:    z.string().max(10).default('PDF'),
  language:    z.string().max(5).optional(),
  year:        z.number().int().optional(),
  author:      z.string().max(300).optional(),
  isPublic:    z.boolean().default(true),
  sortOrder:   z.number().int().default(0),
})

export const createBibliographySchema = z.object({
  authors:   z.string().min(2).max(500),
  title:     z.string().min(3).max(500),
  publisher: z.string().max(300).optional(),
  year:      z.number().int().optional(),
  journal:   z.string().max(300).optional(),
  volume:    z.string().max(50).optional(),
  pages:     z.string().max(50).optional(),
  isbn:      z.string().max(30).optional(),
  doi:       z.string().max(200).optional(),
  url:       z.string().url().optional(),
  type:      z.enum(['BOOK','ARTICLE','THESIS','WEB','DOCUMENT']).default('BOOK'),
  language:  z.string().max(5).optional(),
  notes:     z.string().max(1000).optional(),
  sortOrder: z.number().int().default(0),
})

export const createPilgrimageSchema = z.object({
  name:         z.string().min(3).max(300),
  description:  z.string().optional(),
  location:     z.string().min(2).max(300),
  lat:          z.number().optional(),
  lng:          z.number().optional(),
  websiteUrl:   z.string().url().optional(),
  contactEmail: z.string().email().optional(),
  phone:        z.string().max(30).optional(),
  organizer:    z.string().max(300).optional(),
  frequency:    z.string().max(200).optional(),
  nextDate:     z.string().datetime().optional(),
  imageUrl:     z.string().url().optional(),
  sortOrder:    z.number().int().default(0),
})
